name: My Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Inside action file"
      # - name: Run Code Coverage
      #   uses: workflows/test-cc.yml